[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.33.0"
vulkano-util = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.3"

[profile.dev]
opt-level = 1

# Future dependencies for the engine
#egui_winit_vulkano = "0.24.0"
